### ISSUE TITLE
Failed to connect to non-global ctrl_ifname: wlan0  error: No such file or directory

### ISSUE THREAD

**Issue by miloshev** [0unknwn/auto-hotspot#2]
H, with the latest buster lite i get Failed to connect to non-global ctrl_ifname: wlan0  error: No such file or directory. When the script executes wpa_cli. Couldnt find a fix for it.

**Comment by 0unknwn** [comment]
I get this error as well, but it works nevertheless, so I didn't investigate this.
The `wpa_cli.service` restarts itself on failure, so you can ignore this failure, if it is running. (Check with `systemctl status wpa_cli*`.) The service is started to early but I didn't find the right `After`-statement to get rid of this error. Let me know if you found a solution!

**Comment by miloshev** [comment]
It does not work. No connection to my wifi or hotspot created by the device. Also the systemctl status wpa_cli* returns nothing.

**Comment by miloshev** [comment]
Ok, i have fixed it. etc/network/interfaces file is now:
auto wlan0
allow-hotplug wlan0
    iface wlan0 inet manual
    pre-up wpa_supplicant -i wlan0 -c /etc/wpa_supplicant/wpa_supplicant.conf -B

**Comment by 0unknwn** [comment]
You shouldn't use old style debian networking with this script. So no fiddling around with /etc/network/interfaces.

**Comment by miloshev** [comment]
Ok, wlan0 was not coming up automatically. What is the right way to do it? As i said it works now with the change in the interfaces file

**Comment by 0unknwn** [comment]
You should use a plain Raspbian, because I have only tested with it. Then the install script will do everything for you.

**Comment by miloshev** [comment]
Can you please tell me which is the plain Raspbian? I am using The latest lite version from the site. Should i use the full, or some specific version?

**Comment by 0unknwn** [comment]
The recent lite version is totally fine. But just create the `wpa_supplicant-wlan0.conf` file and run the install script. Don't use `network/interfaces` or any other networking services.
