### ISSUE TITLE
Resolve.conf misconfigured

### ISSUE THREAD

**Issue by TheTurkeyDev** [0unknwn/auto-hotspot#5]
Is there a reason who the resolve.conf file is always set to use a loop back ip? My use case needs the pi to be able to resolve a dns address, but from what I've found, it cannot do this due this file not correctly allowing the domain to get resolved. Is there any way to get around this an allow for domains to get resolved when in wifi client mode? Let me know if there is any other information you need.

**Comment by 0unknwn** [comment]
I don’t think it’s misconfigured. You should be able to resolve dns address. You problem has to have another cause I think.

**Comment by TheTurkeyDev** [comment]
Hmmm. I'll go through the process again, maybe it is something else.

**Comment by TheTurkeyDev** [comment]
Yeah, not sure what happened. Went through the whole process again after reimaging the OS and things can resolve still. Sorry for the bad ticket, but thanks for your time!
