### ISSUE TITLE
Help to run auto-hotspot

### ISSUE THREAD

**Issue by Lippsson** [0unknwn/auto-hotspot#8]
Hello!

I have a updated bullseye running on a raspberry 3A
I did the install steps and configured the /etc/wpa_supplicant/wpa_supplicant-device.conf
like in the example but with 

also when i try to sudo auto-hotspot --start-ap
i get the message: failed to connect to non-global ctrl_iframe: wlan0 error
I´m out off ideas where to troubleshoot

![image](https://user-images.githubusercontent.com/48052340/150528965-0e5e284e-7074-4db4-b389-5b852cbcd4e5.png)

**Comment by 0unknwn** [comment]
What is the output of `ip l`?
I think you might have Predictable Network Interfaces Names enabled. 
If so you can disable it with `raspi-config` or replace `wlan0` with the actual name.

**Comment by Lippsson** [comment]
Thanks for fast responce. I maked ensure that Predictable Network Intercases Names are disabeld
I restart and the ip l output is:
![image](https://user-images.githubusercontent.com/48052340/150538041-64ee763d-88b7-41f7-b853-a1ee9b987e5e.png)

**Comment by 0unknwn** [comment]
And the name of the config file is `/etc/wpa_supplicant/wpa_supplicant-wlan0.conf` right?

**Comment by Lippsson** [comment]
Uhh. Here was my fault. Instead to use wlan0 i named it device. I resaved the file and now i can access my Pi again. Thank a lot for your help!

**Comment by 0unknwn** [comment]
You are very welcome!
